 version: '2'
 services:
   db:
     image: postgres
   web:
     build: .
     # docker hack to make the web container start after the db container is ready.
     command: bash -c "while ! nc -w 1 -z db 5432; do sleep 0.1; done; ./run.sh;"
     ports:
       - "8000:8000"
     depends_on:
       - db