 version: '2'
 services:
   db:
     image: docker.io/postgres:latest
     environment:
       - POSTGRES_HOST_AUTH_METHOD=trust # FIXME: change this for production use!
   web:
     build: .
     environment:
      - PORT
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - ALLOWED_HOSTS
      - DEBUG
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_SSL_CERTFILE
      - EMAIL_SSL_KEYFILE
      - EMAIL_USE_SSL
      - EMAIL_USE_TLS
      - LANGUAGE_CODE
      - TIMEZONE
     # docker hack to make the web container start after the db container is ready.
     command: bash -c "while ! nc -w 1 -z db 5432; do sleep 0.1; done; ./run.sh;"
     ports:
      - "${PORT}:8000"
     depends_on:
       - db
